import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#171305",
        "surface-dim": "#171305",
        surface: "#171305",
        "surface-bright": "#3e3926",
        "surface-container-lowest": "#110e02",
        "surface-container-low": "#1f1c0b",
        "surface-container": "#23200f",
        "surface-container-high": "#2e2a18",
        "surface-container-highest": "#393522",
        "on-surface": "#ebe2c8",
        "on-surface-variant": "#d5c4af",
        "inverse-surface": "#ebe2c8",
        "inverse-on-surface": "#35301e",
        outline: "#9d8e7c",
        "outline-variant": "#504535",
        "surface-tint": "#fdba49",
        primary: "#ffc66b",
        "on-primary": "#432c00",
        "primary-container": "#e8a838",
        "on-primary-container": "#5f3f00",
        "inverse-primary": "#805600",
        secondary: "#a4c9ff",
        "on-secondary": "#00315d",
        "secondary-container": "#0164b4",
        "on-secondary-container": "#d0e1ff",
        tertiary: "#eac9b4",
        "on-tertiary": "#402c1e",
        "tertiary-container": "#cdae9a",
        "on-tertiary-container": "#584132",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffddaf",
        "primary-fixed-dim": "#fdba49",
        "on-primary-fixed": "#281800",
        "on-primary-fixed-variant": "#614000",
        "secondary-fixed": "#d4e3ff",
        "secondary-fixed-dim": "#a4c9ff",
        "on-secondary-fixed": "#001c39",
        "on-secondary-fixed-variant": "#004883",
        "tertiary-fixed": "#fedcc7",
        "tertiary-fixed-dim": "#e1c0ac",
        "on-tertiary-fixed": "#29180b",
        "on-tertiary-fixed-variant": "#594233",
        "on-background": "#ebe2c8",
        "surface-variant": "#393522",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        meridian: "1.5rem",
        horizon: "4rem",
        "fluid-gap": "2.5rem",
        drip: "0.75rem",
      },
      fontFamily: {
        "headline-lg": ["var(--font-epilogue)", "sans-serif"],
        "headline-md": ["var(--font-epilogue)", "sans-serif"],
        "body-lg": ["var(--font-newsreader)", "serif"],
        "body-md": ["var(--font-newsreader)", "serif"],
        "label-sm": ["var(--font-space-grotesk)", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.1", fontWeight: "200", letterSpacing: "-0.04em" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "300" }],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.0", fontWeight: "500", letterSpacing: "0.1em" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};

export default config;
